### ISSUE TITLE
MP4

### ISSUE THREAD

**Issue by squiddickod** [github/vscode-github-actions#275]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/github/vscode-github-actions/pull/272
- [ ] https://github.com/github/vscode-github-actions/issues/267
- [ ] https://github.com/github/vscode-github-actions/pull/274
- [ ] https://github.com/github/vscode-github-actions/issues/12
- [ ] https://github.com/github/vscode-github-actions/issues/139
- [ ] https://github.com/github/vscode-github-actions/issues/190
- [ ] https://github.com/github/vscode-github-actions/issues/270
- [ ] https://github.com/github/vscode-github-actions/issues/67
- [ ] https://github.com/github/vscode-github-actions/issues/268
- [ ] https://github.com/github/vscode-github-actions/issues/266
- [ ] https://github.com/github/vscode-github-actions/issues/103
- [ ] https://github.com/github/vscode-github-actions/issues/92
- [ ] https://github.com/github/vscode-github-actions/issues/73
- [ ] https://github.com/github/vscode-github-actions/pull/269
- [ ] https://github.com/github/vscode-github-actions/issues/265
- [ ] https://github.com/github/vscode-github-actions/issues/264
- [ ] https://github.com/github/vscode-github-actions/issues/90
- [ ] https://github.com/github/vscode-github-actions/issues/241
- [ ] https://github.com/github/vscode-github-actions/issues/75
- [ ] https://github.com/github/vscode-github-actions/issues/222
- [ ] https://github.com/github/vscode-github-actions/issues/198
```

```[tasklist]
### Tasks
- [ ] https://github.com/github/vscode-github-actions/pull/272
```
