### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by laylow12345** [github/vscode-github-actions#384]
**Describe the bug**

**To Reproduce**
1. With this workflow '...'
2. Do this '...'
3. See error

**Expected behavior**

**Screenshots**

**Extension Version**
`v1.x.y`

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/github/vscode-github-actions/pull/382
- [ ] https://github.com/github/vscode-github-actions/issues/77
- [ ] https://github.com/github/vscode-github-actions/issues/381
```
